source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UIBezierPathOvalSegment_Example' do
  pod "UIBezierPathOvalSegment", :path => "../"
end

target 'UIBezierPathOvalSegment_Tests' do
  pod "UIBezierPathOvalSegment", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
